services:
  db:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGODB_INITDB_DATABASE: bms
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - ./db-data/mongodb/:/var/lib/mongodb 
      
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - db
    environment: 
      ME_CONFIG_MONGODB_SERVER : db
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports: 
      - '8081:8081'
    volumes: 
      -  ./db-data/mongoui/:/var/lib/mongoui